/*
 * This source file was generated by the Gradle 'init' task
 */
package net.tabletopmc.patcher;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

/**
 * A simple 'hello world' plugin.
 */
class TabletopPatcherPlugin implements Plugin<Project> {
  @Override
  public void apply(Project project) {
    // Register a task
    project.getTasks().register("greeting", task ->
        task.doLast(_ -> System.out.println("Hello from plugin 'net.tabletopmc.tabletop-patcher'"))
    );
  }
}
