/*
 * This source file was generated by the Gradle 'init' task
 */
package net.tabletopmc.patcher;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class TabletopPatcherPluginTest {
  @Test
  void pluginRegistersTask() {
    // Create a test project and apply the plugin
    Project project = ProjectBuilder.builder().build();
    project.getPlugins().apply("net.tabletopmc.tabletop-patcher");

    // Verify the result
    assertNotNull(project.getTasks().findByName("greeting"));
  }
}
